"""
Generate a minimal DCD test fixture (CHARMM little-endian format).

Produces water.dcd: 3 atoms (O, H, H), 5 frames, orthorhombic unit cell.
Coordinates match water.gro at frame 0 for cross-validation.
"""

import struct
import math

# 3 atoms, 5 frames
N_ATOMS = 3
N_FRAMES = 5

# Per-frame coordinates (Angstroms): O, H1, H2 arranged as simple water
# Frame 0 is the reference; subsequent frames oscillate slightly.
FRAMES = [
    # [x, y, z] per atom
    [[0.00, 0.00, 0.00], [0.96, 0.00, 0.00], [0.00, 0.96, 0.00]],
    [[0.05, 0.05, 0.05], [1.01, 0.05, 0.05], [0.05, 1.01, 0.05]],
    [[0.10, 0.00, 0.00], [1.06, 0.00, 0.00], [0.10, 0.96, 0.00]],
    [[0.05, 0.05, 0.05], [1.01, 0.05, 0.05], [0.05, 1.01, 0.05]],
    [[0.00, 0.00, 0.00], [0.96, 0.00, 0.00], [0.00, 0.96, 0.00]],
]

# Unit cell parameters (Angstroms): a=10, b=10, c=10, angles=90
CELL_A = 10.0
CELL_B = 10.0
CELL_C = 10.0
CELL_ALPHA = 90.0
CELL_BETA = 90.0
CELL_GAMMA = 90.0

TIMESTEP_AKMA = 0.5   # ~24.4 fs per step
NSAVC = 1             # save every step


def write_fortran_record(f, data: bytes):
    """Write a Fortran unformatted binary record (little-endian)."""
    size = len(data)
    f.write(struct.pack('<I', size))
    f.write(data)
    f.write(struct.pack('<I', size))


def make_header():
    """Build the 84-byte DCD header block (CHARMM little-endian)."""
    # Layout (all little-endian int32 unless noted):
    #  0- 3: "CORD"
    #  4- 7: NSET (n_frames)
    #  8-11: ISTART
    # 12-15: NSAVC
    # 16-19: NSTEP
    # 20-35: 4 zeros
    # 36-39: NFREAT (0 = all free)
    # 40-43: DELTA (float32, CHARMM)
    # 44-47: HAS_CELL (1 = crystal)
    # 48-79: 8 zeros
    # 80-83: CHARMM_VERSION
    data = b"CORD"
    data += struct.pack('<i', N_FRAMES)     # NSET
    data += struct.pack('<i', 0)            # ISTART
    data += struct.pack('<i', NSAVC)        # NSAVC
    data += struct.pack('<i', N_FRAMES)     # NSTEP
    data += struct.pack('<4i', 0, 0, 0, 0)  # 4 zeros
    data += struct.pack('<i', 0)            # NFREAT
    data += struct.pack('<f', TIMESTEP_AKMA) # DELTA (float32)
    data += struct.pack('<i', 1)            # HAS_CELL = 1
    data += struct.pack('<8i', 0, 0, 0, 0, 0, 0, 0, 0)  # 8 zeros
    data += struct.pack('<i', 24)           # CHARMM_VERSION (non-zero)
    assert len(data) == 84, f"Header is {len(data)} bytes, expected 84"
    return data


def make_title():
    """Build title block: 1 line of 80 chars."""
    n_titles = 1
    title_line = b"Generated by megane test suite (generate_test_dcd.py)           "
    # Pad/trim to exactly 80 bytes
    title_line = title_line[:80].ljust(80)
    data = struct.pack('<i', n_titles) + title_line
    return data


def make_natom():
    """4-byte NATOM block."""
    return struct.pack('<i', N_ATOMS)


def make_cell():
    """48-byte unit cell record: 6 float64 in CHARMM order A, gamma, B, beta, alpha, C."""
    return struct.pack('<dddddd',
                       CELL_A,
                       CELL_GAMMA,
                       CELL_B,
                       CELL_BETA,
                       CELL_ALPHA,
                       CELL_C)


def main():
    with open("water.dcd", "wb") as f:
        write_fortran_record(f, make_header())
        write_fortran_record(f, make_title())
        write_fortran_record(f, make_natom())

        for coords in FRAMES:
            write_fortran_record(f, make_cell())

            xs = struct.pack('<' + 'f' * N_ATOMS, *[c[0] for c in coords])
            ys = struct.pack('<' + 'f' * N_ATOMS, *[c[1] for c in coords])
            zs = struct.pack('<' + 'f' * N_ATOMS, *[c[2] for c in coords])
            write_fortran_record(f, xs)
            write_fortran_record(f, ys)
            write_fortran_record(f, zs)

    print("Wrote water.dcd")
    print(f"  {N_ATOMS} atoms, {N_FRAMES} frames")
    print(f"  Frame 0 atom 0: {FRAMES[0][0]}")
    print(f"  Frame 0 atom 1: {FRAMES[0][1]}")
    print(f"  Frame 0 atom 2: {FRAMES[0][2]}")


if __name__ == "__main__":
    import os
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    main()
