import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * The docs are organized around two reader tracks that share a common
 * Reference and API section:
 *
 *   - useSidebar    ("Use megane")   — for people who want to look at data
 *   - buildSidebar  ("Build with megane") — for people embedding / scripting megane
 *   - referenceSidebar — lookup tables shared by both tracks
 *   - apiSidebar    — autogenerated Python + TypeScript API
 *
 * Docs live at the site root (routeBasePath: "/"), so moving a page between
 * sidebars never changes its URL — only its navigation context.
 */
const sidebars: SidebarsConfig = {
  useSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: ["introduction", "getting-started"],
    },
    {
      type: "category",
      label: "Visualize Your Data",
      collapsed: false,
      items: [
        { type: "doc", id: "guide/jupyter", label: "Jupyter widget" },
        { type: "doc", id: "guide/cli", label: "Standalone web app" },
      ],
    },
    {
      type: "category",
      label: "Pipelines",
      collapsed: false,
      items: ["guide/pipeline/index"],
    },
  ],

  buildSidebar: [
    {
      type: "category",
      label: "Embed the Viewer",
      collapsed: false,
      items: [
        { type: "doc", id: "guide/web", label: "React component (npm)" },
        "guide/integrations",
      ],
    },
    {
      type: "category",
      label: "Pipeline API",
      collapsed: false,
      items: [
        "guide/pipeline/python",
        "guide/pipeline/typescript",
        "guide/pipeline/json",
      ],
    },
    {
      type: "category",
      label: "Internals",
      collapsed: false,
      items: ["dev/architecture"],
    },
  ],

  referenceSidebar: [
    "reference/node-reference",
    "platform-support",
    {
      type: "doc",
      id: "configuration",
      label: "Configuration",
    },
  ],

  apiSidebar: [
    "api/index",
    {
      type: "autogenerated",
      dirName: "api/python",
    },
    {
      type: "autogenerated",
      dirName: "api/typescript",
    },
  ],
};

export default sidebars;
