import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: ["getting-started", "configuration"],
    },
    {
      type: "category",
      label: "Pipeline",
      items: ["guide/pipeline"],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guide/jupyter",
        "guide/cli",
        "guide/web",
        "guide/integrations",
      ],
    },
  ],
  apiSidebar: [
    "api/index",
    {
      type: "autogenerated",
      dirName: "api/python",
    },
    {
      type: "autogenerated",
      dirName: "api/typescript",
    },
  ],
};

export default sidebars;
