import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: ["introduction", "getting-started"],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guide/jupyter",
        "guide/cli",
        "guide/web",
        "guide/integrations",
      ],
    },
    {
      type: "category",
      label: "Visualization Pipeline",
      items: [
        "guide/pipeline/index",
        "guide/pipeline/python",
        "guide/pipeline/typescript",
        "guide/pipeline/json",
      ],
    },
    {
      type: "category",
      label: "Developer Internals",
      items: ["dev/architecture"],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        "platform-support",
        {
          type: "doc",
          id: "configuration",
          label: "Development Setup",
        },
      ],
    },
  ],
  apiSidebar: [
    "api/index",
    {
      type: "autogenerated",
      dirName: "api/python",
    },
    {
      type: "autogenerated",
      dirName: "api/typescript",
    },
  ],
};

export default sidebars;
